### ISSUE TITLE
Samsung Galaxy SM-G530F panel not working on pmOS.

### ISSUE THREAD

**Issue by BaranSenkul** [msm8916-mainline/linux-panel-drivers#17]
Hello! after successfully installing postmarketOS to my Samsung Galaxy Grand Prime (SM-G530F). After the samsung splash, the panel fades out to a black screen, After some research, it seems that the panel is not recognized. Here is my lk2nd screen:
![photo_2022-07-30_22-13-17](https://user-images.githubusercontent.com/75718738/181948271-d71680fd-8ca9-4d0b-8d50-dc5d043cb95b.jpg)

**Comment by BaranSenkul** [comment]
Update: phone boots up with no display, i can ssh into the phone..

**Comment by BaranSenkul** [comment]
Update: phone boots up with no display. can ssh into the device

**Comment by stephan-gh** [comment]
Please post the `fastboot oem lk_log && fastboot get_staged log.txt`.

**Comment by BaranSenkul** [comment]
Hello! My phone is not seen by fastboot devices in fastboot mode, i set up
the android udev rules, tried many distros but lk2 d just doesn't wanna
appear on my pc using fastboot devices, i installed pmOS by twrp.

**Comment by stephan-gh** [comment]
Ah right. It seems like we don't have support for SM-G530F (without Z at the end) yet, so you'll need to make some changes similar to https://github.com/msm8916-mainline/lk2nd/commit/1d71f236f4f69f5aa338d970eff0cf5c68236779.

Consider joining the [postmarketOS mainline chat room](https://wiki.postmarketos.org/wiki/Matrix_and_IRC), there are people there that can likely help you with the necessary changes.

**Comment by wonderfulShrineMaidenOfParadise** [comment]
We have new matrix room now. Please join [#msm8916:postmarketos.org](https://matrix.to/#/#msm8916:postmarketos.org) if you still need help with porting.
