### ISSUE TITLE
Can you make an image for me?

### ISSUE THREAD

**Issue by yazhuo-wyze** [msm8916-mainline/linux-panel-drivers#30]
Because of my technical reasons. 
I'm not familiar with this piece. 
I use redmi2.wt88047.
pannel nt35521s. 
But the screen can't light up.

image url: 
https://github.com/Project-DragonPi/mobian-wt88047/releases/tag/20210828

Can someone help me extract a screen driver and put it into this image?

Here you can extract the screen driver

https://images.postmarketos.org/bpo/v22.12/xiaomi-wt88047/phosh/20230528-1653/

**Comment by yazhuo-wyze** [comment]
thanks

**Comment by stephan-gh** [comment]
Sorry, unfortunately we cannot provide support for other projects here. You should ask them to get a build with an updated Linux kernel and the new panel drivers.

Alternatively you could also just use the postmarketOS builds you have linked. They have support for the panel you need.
