### ISSUE TITLE
Add more panel to wt88047

### ISSUE THREAD

**Issue by nexustar** [msm8916-mainline/linux-panel-drivers#5]
I  installed postmarketos on my redmi2, it booted but display nothing(blackscreen). I SSH to it and dmesg shows as :
msm_dsi_manager_register: failed to register mipi dsi host for DSI 0
pwm-backlight backlight: supply power not found, using dummy regulator
I fonud lineageos seems to support more panel , maybe my phone use one of it (it can boot to lineageos successfully) https://github.com/LineageOS/android_kernel_wingtech_msm8916/tree/lineage-17.1/arch/arm/boot/dts/qcom/wt88047

**Comment by Minecrell** [comment]
It's easier if you join the chat on [Matrix/IRC](https://wiki.postmarketos.org/wiki/Matrix_and_IRC), then I can provide you a boot image for testing.
